url: https://www.williamghelfi.com
baseurl: /
title: Born, Growing Up.
subtitle: William Ghelfi
author: William Ghelfi
simple_search: false
description:

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

plugins:
    - jekyll-paginate
    - jekyll-gist
    - jekyll-archives

jekyll-archives:
    enabled:
        - categories
    layouts:
        category: category_index

paginate: 1          # Posts per page on the blog index
paginate_path: blog/page/:num  # Directory base for pagination URLs eg. /blog/page/2/
excerpt_link: "Continue →"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

sitemap:
    exclude:
        - "/atom.xml"
        - "/salesbury-1.0.0/index.html"
        - "/salesbury-1.0.0/js/salesbury-demo.js"
        - "/robots.txt"
    include_posts:
        - "/index.html"

exclude:
  - divshot.json

